pipeline {
    agent any

    stages {

        stage('Build & Tag Docker Image') {
            steps {
                script {

                    withDockerRegistry(credentialsId: 'docker-cred') {

                        sh '''
                        docker build -f rag_backend/Dockerfile \
                        -t abhishekkadam2003/rag-backend:latest .
                        '''

                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {

                    withDockerRegistry(credentialsId: 'docker-cred') {

                        sh 'docker push abhishekkadam2003/rag-backend:latest'

                    }
                }
            }
        }
    }
}
